### ISSUE TITLE
Issues regarding reproduction

### ISSUE THREAD

**Issue by nifris323** [ZiQi-Jiang/CLIPDrag#1]
Hi. Thank you for your interesting work.
I have been trying to reproduce your results as described in the paper and the repository, but I have been facing some issues.
Here I post the detailed process I have undergone and some results that do not correspond to the reported results.

[https://docs.google.com/document/d/1iOvF5s_6Vfdot-8bVnv4x4DU8jl9qHdXJd9cto1NWgo/edit?usp=sharing](https://docs.google.com/document/d/1iOvF5s_6Vfdot-8bVnv4x4DU8jl9qHdXJd9cto1NWgo/edit?usp=sharing)

I would appreciate if you could suggest any additional configurations, preprocessing steps, or implementation details I have missed for the reproduction. Thank you in advance.

**Comment by ZiQi-Jiang** [comment]
Thanks for your interest in our work, and I am very grateful for the feedback. 

I noticed a few mistakes while organizing the code, and I've corrected them now. Please use the updated version. My apologies for the inconvenience.

And for your problems,  you’d better follow the default settings in the paper: set fuse_cof = 0.7, and number of pixel steps=800 to get better results.  I have set them as default settings in the new version.

I have sent a similar email to you which contains an example.

Thanks.

**Comment by nifris323** [comment]
Thank you very much for your prompt feedback.

However, I’ve realized that I inadvertently ran the wrong script, `run_drag_diffusion.py` instead of your intended `run_clip_drag.py`. Nevertheless, the code execution still failed due to a missing function: `drag_diffusion_update_final`, which seems to be your main difference with DragDiffusion.

I would greatly appreciate it if you could provide or update the implementation for this function.
